services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ministry_database
    environment:
      POSTGRES_DB: ministry_lands
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5435:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  api:
    image: node:18-alpine
    container_name: ministry_api
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: